### ISSUE TITLE
Crash after injection

### ISSUE THREAD

**Issue by dagmenico** [myfreeweb/node-red-contrib-nut-ups#4]
I'm getting the following error after I trigger the nut-ups node with an injection. After this error Node-RED crashes and I need to restart it.

Error: spawn upsc ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by valpackett** [comment]
Well, do you have the `upsc` binary from NUT installed and accessible on `$PATH`?

**Comment by moose75** [comment]
Hi ! Same problem here on my Raspberry PI. The upsc binary is working well under shell and accessible on $PATH. 
Here is the log trace :
```
Nov 21 18:08:49 raspberrypi Node-RED[598]: 21 Nov 18:08:49 - [red] Uncaught Exception:
Nov 21 18:08:49 raspberrypi Node-RED[598]: 21 Nov 18:08:49 - TypeError: Cannot create property 'low' on string '100'
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at /home/pi/.node-red/node_modules/node-red-contrib-nut-ups/nut-ups/nut-ups.js:26:38
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at Array.forEach (native)
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at /home/pi/.node-red/node_modules/node-red-contrib-nut-ups/nut-ups/nut-ups.js:17:24
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at ChildProcess.exithandler (child_process.js:189:7)
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at emitTwo (events.js:106:13)
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at ChildProcess.emit (events.js:191:7)
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at maybeClose (internal/child_process.js:920:16)
Nov 21 18:08:49 raspberrypi Node-RED[598]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Nov 21 18:08:49 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE

```
Any help is welcome !
Thanks

**Comment by dagmenico** [comment]
myfreeweb you're right. Node-RED is running on a Mac (the UPS is attached to a Qnap NAS) and I've discovered that upsc command isn't available.
I'll try to resolve installing upsc if I find an available version. Tnx

**Comment by valpackett** [comment]
Yeah you'll need to run something like `brew install nut` (with [Homebrew](https://brew.sh/))

**Comment by moose75** [comment]
Hi myfreeweb !
Why did you close the issue ? 
I've NUT installed and working on a Raspberry PI .. and got the same issue .. Node-RED crashes .. 
Please see my post above .. 
Thanks

**Comment by valpackett** [comment]
@moose75 because this is not the same issue, you should've created a new one.

I think I know what's happening in your stack trace. You're using an old version ~~. Well, the latest one on npm probably :D try git master instead. Actually, I'll release a version right now~~ Try 1.0.2

**Comment by moose75** [comment]
ok @myfreeweb, sorry about not opening a new issue .. I was thinking it was the same problem.
I'll upgrade asap to 1.0.2 and let you know . Thx

**Comment by moose75** [comment]
@myfreeweb 1.0.2 works like a charm !
Thanks a lot for your support
