### ISSUE TITLE
Error: spawn upsc ENOENT

### ISSUE THREAD

**Issue by wizzywik** [myfreeweb/node-red-contrib-nut-ups#7]
Getting this eror all the time. What do I do wrong?

**Comment by valpackett** [comment]
Do you have `upsc` installed and on your `$PATH`?

Maybe your distribution has the nut client stuff in a separate package

**Comment by wizzywik** [comment]
NUT running on a Synology (default install), Node-red running in Docker on same Synology. I can get access to the data from other devices, so I think serverside is ok...
(sorry, I'm not an IT pro...)

**Comment by valpackett** [comment]
your docker container thing needs to have nut installed in it

**Comment by wizzywik** [comment]
Thanks so far, I will contact my local expert to do these installs.
